Repository eclipse-zenoh/zenoh-pico, pull requests merged in 2024-09, with the labels that each got.

#596 Fix and simplify cmake package config
  CMakeLists.txt
  PackageConfig.cmake.in
  examples/CMakeLists.txt
Labels: enhancement, release

#620 Change `z_id_to_string` parameters order
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: bug, api sync

#622 Add z_view_string_from_substr and fix z_view_string_empty
  docs/api.rst
  include/zenoh-pico/api/olv_macros.h
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement

#624 Add z_string_as_slice
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement

#623 Add z_keyexpr_canonize_null_terminated
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement

#629 add functionality to iterate over z_bytes slices
  docs/api.rst
  include/zenoh-pico/api/macros.h
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  src/api/api.c
  tests/z_api_bytes_test.c
  zenohpico.pc
Labels: enhancement, api sync

#630 Switch reliability from subscriber to publisher.
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  include/zenoh-pico/config.h
  include/zenoh-pico/net/primitives.h
  include/zenoh-pico/net/publish.h
  include/zenoh-pico/net/sample.h
  include/zenoh-pico/net/subscribe.h
  include/zenoh-pico/protocol/core.h
  include/zenoh-pico/protocol/definitions/declarations.h
  include/zenoh-pico/protocol/definitions/network.h
  include/zenoh-pico/protocol/definitions/transport.h
  include/zenoh-pico/session/push.h
  include/zenoh-pico/session/session.h
  include/zenoh-pico/session/subscription.h
  src/api/api.c
  src/net/primitives.c
  src/net/sample.c
  src/net/subscribe.c
  src/protocol/codec/declarations.c
  src/protocol/definitions/declarations.c
  src/protocol/definitions/network.c
  src/protocol/definitions/transport.c
  src/session/interest.c
  src/session/push.c
  src/session/rx.c
  src/session/subscription.c
  src/transport/multicast/rx.c
  src/transport/unicast/rx.c
  tests/z_msgcodec_test.c
Labels: enhancement

#636 Use session weak in user owned entities
  include/zenoh-pico/collections/refcount.h
  include/zenoh-pico/net/publish.h
  include/zenoh-pico/net/query.h
  include/zenoh-pico/net/subscribe.h
  include/zenoh-pico/utils/result.h
  src/api/api.c
  src/net/primitives.c
  src/net/publish.c
  src/net/query.c
  src/net/subscribe.c
Labels: enhancement, api sync

#638 Fix make_decl_queryable argument order
  include/zenoh-pico/protocol/definitions/declarations.h
  src/protocol/definitions/declarations.c
Labels: bug

#644 Remove legacy _Z_OWNED_FUNCTIONS_PTR_IMPL macro
  include/zenoh-pico/api/olv_macros.h
Labels: enhancement

#641 Remove legacy z_config_peer/z_config_client methods
  CMakeLists.txt
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  src/api/api.c
  tests/z_api_config_test.c
Labels: enhancement

#646 Fix request timeout u64 error
  include/zenoh-pico/api/types.h
  include/zenoh-pico/net/primitives.h
  include/zenoh-pico/protocol/definitions/network.h
  src/net/primitives.c
  src/protocol/codec/network.c
  src/protocol/definitions/network.c
  tests/z_msgcodec_test.c
Labels: bug

#645 Remove clone for types which do not involve copying
  include/zenoh-pico/api/macros.h
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement

#648 Unify z_config_clone definition
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement

#650 Fix arduino examples
  examples/arduino/z_get.ino
  examples/arduino/z_pub.ino
  examples/arduino/z_pull.ino
  examples/arduino/z_queryable.ino
  examples/arduino/z_sub.ino
Labels: bug

#654 fix z_id_to_string signature
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: bug

#653 Remove const from closure params
  examples/arduino/z_get.ino
  examples/arduino/z_queryable.ino
  examples/arduino/z_scout.ino
  examples/arduino/z_sub.ino
  examples/espidf/z_get.c
  examples/espidf/z_queryable.c
  examples/espidf/z_scout.c
  examples/espidf/z_sub.c
  examples/freertos_plus_tcp/z_get.c
  examples/freertos_plus_tcp/z_queryable.c
  examples/freertos_plus_tcp/z_scout.c
  examples/freertos_plus_tcp/z_sub.c
  examples/freertos_plus_tcp/z_sub_st.c
  examples/mbed/z_get.cpp
  examples/mbed/z_queryable.cpp
  examples/mbed/z_scout.cpp
  examples/mbed/z_sub.cpp
  examples/unix/c11/z_get.c
  examples/unix/c11/z_get_attachment.c
  examples/unix/c11/z_ping.c
  examples/unix/c11/z_pong.c
  examples/unix/c11/z_queryable.c
  examples/unix/c11/z_queryable_attachment.c
  examples/unix/c11/z_scout.c
  examples/unix/c11/z_sub.c
  examples/unix/c11/z_sub_attachment.c
  examples/unix/c11/z_sub_st.c
  examples/unix/c11/z_sub_thr.c
  examples/unix/c99/z_get.c
  examples/unix/c99/z_ping.c
  examples/unix/c99/z_pong.c
  examples/unix/c99/z_queryable.c
  examples/unix/c99/z_scout.c
  examples/unix/c99/z_sub.c
  examples/unix/c99/z_sub_st.c
  examples/windows/z_get.c
  examples/windows/z_ping.c
  examples/windows/z_pong.c
  examples/windows/z_queryable.c
  examples/windows/z_scout.c
  examples/windows/z_sub.c
  examples/windows/z_sub_st.c
  examples/zephyr/z_get.c
  examples/zephyr/z_queryable.c
  examples/zephyr/z_scout.c
  examples/zephyr/z_sub.c
  include/zenoh-pico/api/handlers.h
  include/zenoh-pico/api/macros.h
  include/zenoh-pico/api/types.h
  include/zenoh-pico/session/session.h
  src/api/api.c
  tests/z_api_alignment_test.c
  tests/z_client_test.c
  tests/z_peer_multicast_test.c
  tests/z_perf_rx.c
  tests/z_test_fragment_rx.c
Labels: enhancement, api sync

#652 Add background declaration
  src/api/api.c
  src/net/primitives.c
  src/net/publish.c
  src/net/query.c
  src/net/subscribe.c
Labels: enhancement, api sync

#655 Update docs about `*_drop` and `z_undecalre_*`
  include/zenoh-pico/api/primitives.h
Labels: documentation

#656 fix session ref count leak in query_reply_err
  src/api/api.c
Labels: bug, internal

#658 update docs regarding undefined behavior when using multiple z_bytes_writers
  include/zenoh-pico/api/primitives.h
Labels: documentation, internal

#660 Add memory leak test
  .github/workflows/build-check.yaml
  CMakeLists.txt
  src/api/api.c
  tests/memory_leak.py
Labels: bug, enhancement

#674 Add methods for z_owned_strings_array_t creation:
  include/zenoh-pico/api/types.h
  src/api/api.c
  tests/z_data_struct_test.c
Labels: enhancement, api sync

#672 Add z_priority_default method
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement, api sync

#676 Clarify batch size requirement when operating on multicast
  README.md
Labels: documentation

#677 Rename z_hello_locators to zp_hello_locators and add zenoh-c compatible z_hello_locators
  docs/api.rst
  examples/arduino/z_scout.ino
  examples/espidf/z_scout.c
  examples/freertos_plus_tcp/z_scout.c
  examples/mbed/z_scout.cpp
  examples/unix/c11/z_scout.c
  examples/unix/c99/z_scout.c
  examples/windows/z_scout.c
  examples/zephyr/z_scout.c
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement, api sync

#678 Documnetation page about zenoh-pico types concepts
  docs/concepts.rst
  docs/index.rst
Labels: documentation

#667 Fix compilation issue on esp32-s2
  include/zenoh-pico/system/platform/arduino/esp32.h
  src/system/arduino/esp32/system.c
Labels: bug

#681 Improve `z_sleep_*` error code handling
  include/zenoh-pico/system/platform-common.h
  src/system/arduino/esp32/system.c
  src/system/arduino/opencr/system.c
  src/system/emscripten/system.c
  src/system/espidf/system.c
  src/system/flipper/system.c
  src/system/freertos_plus_tcp/system.c
  src/system/mbed/system.cpp
  src/system/unix/system.c
  src/system/windows/system.c
  src/system/zephyr/system.c
Labels: enhancement

#682 add z_encoding_equals
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement, api sync

#659 switch Z_FEATURE_UNSTABLE_API to #ifdef
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  src/api/api.c
Labels: enhancement, api sync

#673 Add z_bytes example
  docs/api.rst
  docs/conf.py
  examples/CMakeLists.txt
  examples/unix/c11/z_bytes.c
  include/zenoh-pico.h
  include/zenoh-pico.h.in
  include/zenoh-pico/api/constants.h
  include/zenoh-pico/api/encoding.h
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  src/api/api.c
  src/api/encoding.c
  src/system/unix/system.c
Labels: enhancement

#684 Add z_string_array documentation
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
Labels: documentation

#686 Encoding constants fix
  include/zenoh-pico/api/encoding.h
  src/api/encoding.c
Labels: bug

#687 system: arduino: esp32: network: Use socklen_t over uint
  src/system/arduino/esp32/network.cpp
Labels: bug

#688 Remove config token duplicate
  CMakeLists.txt
Labels: bug

#690 Fix potential segfault during multicast cleanup
  src/system/unix/network.c
Labels: bug

#693 chore: update release.yml for required labels
  .github/release.yml
Labels: internal

#694 Add z_view_slice_from_buf method
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement, api sync

#695 Update documentation for view types
  docs/concepts.rst
Labels: documentation

#692 system/arduino/esp32 bugfixes & warnings
  src/system/arduino/esp32/system.c
Labels: bug

#697 Fix docs generation for methods which returns bool
  docs/conf.py
  include/zenoh-pico/api/primitives.h
Labels: bug, documentation
