Repository eclipse-zenoh/zenoh-pico, pull requests merged in 2024-11, with the labels that each got.

#774 Replace exit with return in zephyr examples
  examples/zephyr/z_get.c
  examples/zephyr/z_pub.c
  examples/zephyr/z_pull.c
  examples/zephyr/z_queryable.c
  examples/zephyr/z_sub.c
Labels: bug

#778 Add platform_common.c to zephyr CMakeLists.txt file
  zephyr/CMakeLists.txt
Labels: bug

#772 fix: No tag in dry run
  .github/workflows/release.yml
  ci/scripts/bump-and-tag.bash
Labels: internal

#779 Rework Zenoh ID conversion
  include/zenoh-pico/collections/string.h
  include/zenoh-pico/utils/config.h
  include/zenoh-pico/utils/uuid.h
  src/api/api.c
  src/collections/string.c
  src/net/session.c
  src/protocol/config.c
  src/transport/multicast.c
  src/transport/unicast.c
  src/utils/uuid.c
  tests/z_api_alignment_test.c
  tests/z_client_test.c
  tests/z_data_struct_test.c
  tests/z_peer_multicast_test.c
Labels: bug, enhancement

#777 Improve sub frame decode performance
  CMakeLists.txt
  include/zenoh-pico/collections/bytes.h
  include/zenoh-pico/collections/element.h
  include/zenoh-pico/collections/string.h
  include/zenoh-pico/collections/vec.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  include/zenoh-pico/link/endpoint.h
  include/zenoh-pico/net/reply.h
  include/zenoh-pico/net/sample.h
  include/zenoh-pico/net/session.h
  include/zenoh-pico/protocol/codec/transport.h
  include/zenoh-pico/protocol/core.h
  include/zenoh-pico/protocol/definitions/network.h
  include/zenoh-pico/protocol/definitions/transport.h
  include/zenoh-pico/protocol/ext.h
  include/zenoh-pico/protocol/iobuf.h
  include/zenoh-pico/session/resource.h
  include/zenoh-pico/session/session.h
  include/zenoh-pico/session/subscription.h
  include/zenoh-pico/system/link/raweth.h
  include/zenoh-pico/transport/transport.h
  src/api/api.c
  src/collections/bytes.c
  src/collections/vec.c
  src/net/encoding.c
  src/net/sample.c
  src/protocol/codec.c
  src/protocol/codec/message.c
  src/protocol/codec/network.c
  src/protocol/codec/transport.c
  src/protocol/core.c
  src/protocol/definitions/message.c
  src/protocol/definitions/transport.c
  src/session/interest.c
  src/session/query.c
  src/session/queryable.c
  src/session/resource.c
  src/session/rx.c
  src/session/subscription.c
  src/session/utils.c
  src/transport/multicast/rx.c
  src/transport/unicast/rx.c
  tests/z_msgcodec_test.c
Labels: enhancement

#782 chore: Update org secrets
  .github/workflows/release.yml
Labels: internal

#632 Implement liveliness support
  CMakeLists.txt
  docs/api.rst
  docs/conf.py
  examples/CMakeLists.txt
  examples/unix/c11/z_get_liveliness.c
  examples/unix/c11/z_liveliness.c
  examples/unix/c11/z_sub_liveliness.c
  include/zenoh-pico.h
  include/zenoh-pico.h.in
  include/zenoh-pico/api/handlers.h
  include/zenoh-pico/api/liveliness.h
  include/zenoh-pico/api/macros.h
  include/zenoh-pico/collections/intmap.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  include/zenoh-pico/net/liveliness.h
  include/zenoh-pico/net/primitives.h
  include/zenoh-pico/net/session.h
  include/zenoh-pico/protocol/keyexpr.h
  include/zenoh-pico/session/liveliness.h
  include/zenoh-pico/session/session.h
  include/zenoh-pico/session/subscription.h
  src/api/api.c
  src/api/liveliness.c
  src/collections/fifo_mt.c
  src/collections/intmap.c
  src/net/liveliness.c
  src/net/primitives.c
  src/protocol/keyexpr.c
  src/session/interest.c
  src/session/liveliness.c
  src/session/push.c
  src/session/resource.c
  src/session/rx.c
  src/session/subscription.c
  src/session/utils.c
  tests/z_api_liveliness_test.c
  tests/z_collections_test.c
  tests/z_msgcodec_test.c
Labels: new feature

#786 Merge liveliness in 1.1
  CMakeLists.txt
  docs/api.rst
  docs/conf.py
  examples/CMakeLists.txt
  examples/unix/c11/z_get_liveliness.c
  examples/unix/c11/z_liveliness.c
  examples/unix/c11/z_sub_liveliness.c
  include/zenoh-pico.h
  include/zenoh-pico.h.in
  include/zenoh-pico/api/handlers.h
  include/zenoh-pico/api/liveliness.h
  include/zenoh-pico/api/macros.h
  include/zenoh-pico/collections/intmap.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  include/zenoh-pico/net/liveliness.h
  include/zenoh-pico/net/primitives.h
  include/zenoh-pico/net/query.h
  include/zenoh-pico/net/session.h
  include/zenoh-pico/protocol/keyexpr.h
  include/zenoh-pico/session/liveliness.h
  include/zenoh-pico/session/session.h
  include/zenoh-pico/session/subscription.h
  src/api/api.c
  src/api/liveliness.c
  src/collections/fifo_mt.c
  src/collections/intmap.c
  src/net/liveliness.c
  src/net/primitives.c
  src/net/query.c
  src/protocol/iobuf.c
  src/protocol/keyexpr.c
  src/session/interest.c
  src/session/liveliness.c
  src/session/push.c
  src/session/queryable.c
  src/session/resource.c
  src/session/rx.c
  src/session/subscription.c
  src/session/utils.c
  tests/z_api_liveliness_test.c
  tests/z_client_test.c
  tests/z_collections_test.c
  tests/z_msgcodec_test.c
  tests/z_peer_multicast_test.c
  zenohpico.pc
Labels: enhancement

#787 Fix typo
  docs/api.rst
  include/zenoh-pico/api/liveliness.h
  src/api/liveliness.c
Labels: bug, internal

#788 Mark liveliness API as unstable and disable by default
  CMakeLists.txt
  include/zenoh-pico/config.h
Labels: bug, internal

#791 Add corrections on 1.1
  CMakeLists.txt
  docs/api.rst
  include/zenoh-pico/api/liveliness.h
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/config.h
  include/zenoh-pico/net/primitives.h
  src/api/api.c
  src/transport/multicast/rx.c
  src/transport/unicast/rx.c
  src/transport/unicast/transport.c
Labels: enhancement

#793 Merge main in 1.1
  zenohpico.pc
Labels: enhancement

#798 Fix merge issue
  src/api/liveliness.c
Labels: bug, internal

#803 Fix liveliness cleanup
  include/zenoh-pico/api/liveliness.h
  src/api/liveliness.c
  src/net/liveliness.c
  src/session/liveliness.c
  tests/z_api_liveliness_test.c
Labels: bug

#806 Fix session memory leak during liveliness cleanup
  src/api/liveliness.c
  src/net/liveliness.c
  src/session/liveliness.c
  tests/z_api_liveliness_test.c
Labels: bug

#808 chore: update ssh secrets
  .github/workflows/release.yml
Labels: internal

#811 Add CI memory leak tests for liveliness
  .github/workflows/build-check.yaml
  examples/unix/c11/z_get_liveliness.c
  examples/unix/c11/z_sub_liveliness.c
  tests/memory_leak.py
Labels: internal

#812 Add AddressSanitizer to CI tests
  .github/workflows/build-check.yaml
  CMakeLists.txt
  GNUmakefile
  src/collections/refcount.c
  src/protocol/keyexpr.c
  tests/z_api_encoding_test.c
  tests/z_channels_test.c
  tests/z_collections_test.c
  tests/z_data_struct_test.c
  tests/z_endpoint_test.c
  tests/z_keyexpr_test.c
  tests/z_msgcodec_test.c
  tests/z_refcount_test.c
Labels: internal
