Repository eclipse-zenoh/zenoh-pico, pull requests merged in 2024-10, with the labels that each got.

#699 Build as release by default
  CMakeLists.txt
Labels: bug

#700 Add z_encoding_loan_default
  include/zenoh-pico/api/encoding.h
  src/api/encoding.c
Labels: enhancement, api sync

#701 make serialization stable
  examples/unix/c11/z_bytes.c
  examples/unix/c11/z_get_attachment.c
  examples/unix/c11/z_pub_attachment.c
  examples/unix/c11/z_queryable_attachment.c
  examples/unix/c11/z_sub_attachment.c
  include/zenoh-pico/api/macros.h
  include/zenoh-pico/api/serialization.h
  src/api/serialization.c
  tests/z_api_bytes_test.c
  tests/z_api_null_drop_test.c
Labels: enhancement, api sync

#696 Documentation structure reorganization
  CMakeLists.txt
  docs/api.rst
  docs/conf.py
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  include/zenoh-pico/collections/arc_slice.h
  include/zenoh-pico/system/platform.h
  include/zenoh-pico/system/platform_common.h
  include/zenoh-pico/utils/logging.h
  src/api/api.c
  src/system/arduino/esp32/system.c
  src/system/platform_common.c
  src/system/unix/system.c
  tests/z_refcount_test.c
Labels: documentation

#703 Add z_reliability_default
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement, api sync

#704 Fix z_task_join signature
  include/zenoh-pico/system/platform_common.h
  src/system/platform_common.c
Labels: bug, api sync

#705 Add z_task_detach and z_task_drop methods
  docs/api.rst
  include/zenoh-pico/system/platform_common.h
  src/system/arduino/esp32/system.c
  src/system/arduino/opencr/system.c
  src/system/emscripten/system.c
  src/system/espidf/system.c
  src/system/flipper/system.c
  src/system/freertos_plus_tcp/system.c
  src/system/mbed/system.cpp
  src/system/platform_common.c
  src/system/unix/system.c
  src/system/windows/system.c
  src/system/zephyr/system.c
Labels: enhancement, api sync

#706 Add doc warnings for unstable methods
  docs/api.rst
  include/zenoh-pico/api/constants.h
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/serialization.h
Labels: documentation

#709 serialization support for bool
  docs/api.rst
  include/zenoh-pico/api/serialization.h
  src/api/serialization.c
  tests/z_api_bytes_test.c
Labels: enhancement, api sync

#710 Docs comments celanup, fixes, etc.
  include/zenoh-pico/api/constants.h
  include/zenoh-pico/api/encoding.h
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/serialization.h
  include/zenoh-pico/api/types.h
Labels: documentation

#711 Fix c type formatting in documentation
  include/zenoh-pico/api/serialization.h
Labels: bug, documentation

#714 Improve doc
  docs/api.rst
  docs/concepts.rst
  docs/index.rst
  include/zenoh-pico/api/constants.h
  include/zenoh-pico/api/primitives.h
Labels: enhancement

#716 Add docs for system functions
  docs/api.rst
  include/zenoh-pico/system/platform_common.h
Labels: documentation

#717 Mark zp_time_since_epoch and zp_get_time_since_epoch as internal
  include/zenoh-pico/system/platform_common.h
  src/api/api.c
  src/system/arduino/esp32/system.c
  src/system/arduino/opencr/system.c
  src/system/emscripten/system.c
  src/system/espidf/system.c
  src/system/flipper/system.c
  src/system/freertos_plus_tcp/system.c
  src/system/mbed/system.cpp
  src/system/unix/system.c
  src/system/windows/system.c
  src/system/zephyr/system.c
Labels: internal

#715 Fix -Wpedantic violations when included in C++
  include/zenoh-pico/api/macros.h
Labels: bug

#718 Fix config segfault
  include/zenoh-pico/link/config/raweth.h
  src/link/endpoint.c
  src/protocol/iobuf.c
  src/transport/raweth/link.c
Labels: bug

#719 Remove legacy z_timestamp_check
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement, api sync

#722 Change z_mutex_loan to z_mutex_loan_mut in doc
  docs/api.rst
Labels: documentation

#723 Add Z_FEATURE_TCP_NODELAY
  CMakeLists.txt
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  src/protocol/iobuf.c
  src/system/arduino/esp32/network.cpp
  src/system/espidf/network.c
  src/system/unix/network.c
  src/system/windows/network.c
  src/system/zephyr/network.c
  src/transport/multicast/tx.c
  src/transport/unicast/tx.c
Labels: bug, enhancement

#726 Fix freertos CI build
  .github/workflows/freertos_plus_tcp.yaml
Labels: internal

#728 encoding alignment with zenoh-rust
  docs/api.rst
  examples/unix/c11/z_bytes.c
  include/zenoh-pico/api/encoding.h
  src/api/api.c
  src/api/encoding.c
  tests/z_api_encoding_test.c
Labels: api sync, internal

#727 Set mbed CI to use ubuntu 22.04
  .github/workflows/mbed.yaml
Labels: internal

#729 Use standalone valgrind in place of snap for CI tests
  .github/workflows/build-check.yaml
Labels: internal

#724 Add documentation about bytes reader/writer
  docs/api.rst
  include/zenoh-pico/api/primitives.h
Labels: documentation

#732 Fix parameters order in z_declare_keyexpr/z_undeclare_keyexpr documentation
  include/zenoh-pico/api/primitives.h
Labels: documentation

#733 Remove z_view_string_array_t definition
  include/zenoh-pico/api/types.h
Labels: bug, internal

#734 Align closure handler names
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  include/zenoh-pico/net/primitives.h
  include/zenoh-pico/session/session.h
  src/api/api.c
  src/net/primitives.c
Labels: internal

#735 Fix undefined behavior on udp config
  src/link/endpoint.c
  src/protocol/config.c
Labels: bug

#730 Improve throughput performance (trigger local subscriber focus)
  CMakeLists.txt
  include/zenoh-pico/collections/bytes.h
  include/zenoh-pico/collections/slice.h
  include/zenoh-pico/collections/string.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  include/zenoh-pico/net/encoding.h
  include/zenoh-pico/net/publish.h
  include/zenoh-pico/net/query.h
  include/zenoh-pico/net/reply.h
  include/zenoh-pico/net/sample.h
  include/zenoh-pico/net/subscribe.h
  include/zenoh-pico/protocol/core.h
  include/zenoh-pico/protocol/definitions/declarations.h
  include/zenoh-pico/protocol/definitions/interest.h
  include/zenoh-pico/protocol/definitions/network.h
  include/zenoh-pico/protocol/keyexpr.h
  src/api/api.c
  src/collections/bytes.c
  src/collections/slice.c
  src/collections/string.c
  src/net/encoding.c
  src/net/primitives.c
  src/net/publish.c
  src/net/query.c
  src/net/reply.c
  src/net/sample.c
  src/net/subscribe.c
  src/protocol/core.c
  src/protocol/definitions/declarations.c
  src/protocol/definitions/interest.c
  src/protocol/definitions/network.c
  src/protocol/keyexpr.c
  src/session/interest.c
  src/session/query.c
  src/session/resource.c
  src/session/subscription.c
Labels: enhancement

#737 Improve throughput performance #2 (refcount focus)
  CMakeLists.txt
  include/zenoh-pico/collections/arc_slice.h
  include/zenoh-pico/collections/refcount.h
  include/zenoh-pico/collections/slice.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  include/zenoh-pico/net/sample.h
  include/zenoh-pico/protocol/core.h
  include/zenoh-pico/session/subscription.h
  src/api/api.c
  src/collections/arc_slice.c
  src/collections/refcount.c
  src/collections/slice.c
  src/collections/vec.c
  src/link/link.c
  src/net/encoding.c
  src/net/sample.c
  src/protocol/codec.c
  src/protocol/codec/declarations.c
  src/protocol/codec/message.c
  src/protocol/codec/network.c
  src/protocol/codec/transport.c
  src/session/push.c
  src/session/rx.c
  src/session/scout.c
  src/session/subscription.c
  src/session/utils.c
  src/transport/multicast/read.c
  src/transport/multicast/rx.c
  src/transport/multicast/transport.c
  src/transport/raweth/read.c
  src/transport/unicast/read.c
  src/transport/unicast/rx.c
  src/transport/unicast/transport.c
  tests/z_msgcodec_test.c
  tests/z_refcount_test.c
Labels: enhancement

#736 Update closure handlers documentation
  docs/api.rst
  include/zenoh-pico/api/primitives.h
Labels: documentation

#739 Rename closure callback/dropper types
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  include/zenoh-pico/net/primitives.h
  include/zenoh-pico/session/session.h
  src/api/api.c
  src/net/primitives.c
Labels: bug, api sync

#741 Remove legacy z_zint_t from public API
  docs/api.rst
  include/zenoh-pico/api/types.h
  tests/z_client_test.c
  tests/z_peer_multicast_test.c
Labels: bug, api sync

#743 Rename z_loaned_hello_handler_t to z_closure_hello_callback_t
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  src/api/api.c
Labels: bug, api sync

#744 Add documentation about logging
  docs/api.rst
Labels: documentation

#746 Update README.md
  README.md
Labels: documentation

#748 hardcode clang-format runner to Ubuntu24.04
  .github/workflows/build-check.yaml
Labels: internal

#747 fix build granularity
  include/zenoh-pico/api/handlers.h
  src/api/encoding.c
  zenohpico.pc
Labels: bug

#750 Fix badly named encoding constants
  include/zenoh-pico/api/encoding.h
Labels: bug

#751 Fix package generation
  CMakeLists.txt
  zenohpico.pc
Labels: bug, internal

#753 fix: package version for releases
  CMakeLists.txt
Labels: internal

#749 Improve throughput performance #3 (rx buffer focus)
  examples/unix/c11/z_get_attachment.c
  include/zenoh-pico/collections/arc_slice.h
  include/zenoh-pico/collections/refcount.h
  include/zenoh-pico/net/reply.h
  include/zenoh-pico/protocol/iobuf.h
  include/zenoh-pico/transport/multicast/rx.h
  include/zenoh-pico/transport/raweth/rx.h
  include/zenoh-pico/transport/unicast/rx.h
  src/collections/arc_slice.c
  src/net/reply.c
  src/protocol/codec.c
  src/protocol/iobuf.c
  src/session/query.c
  src/transport/multicast/read.c
  src/transport/multicast/rx.c
  src/transport/raweth/read.c
  src/transport/raweth/rx.c
  src/transport/unicast/read.c
  src/transport/unicast/rx.c
  tests/z_client_test.c
  tests/z_peer_multicast_test.c
  tests/z_refcount_test.c
Labels: enhancement

#754 Improve throughput performance #4 (rx defragmentation focus)
  include/zenoh-pico/protocol/iobuf.h
  include/zenoh-pico/transport/transport.h
  src/net/filtering.c
  src/protocol/codec/transport.c
  src/protocol/iobuf.c
  src/transport/multicast/read.c
  src/transport/multicast/rx.c
  src/transport/peer_entry.c
  src/transport/unicast/rx.c
  src/transport/unicast/transport.c
  tests/z_msgcodec_test.c
Labels: enhancement

#757 build shared lib for packages instead of static one
  ci/scripts/build-linux.bash
Labels: bug

#759 Fix z_task cleanup for platforms with pthread support
  src/system/emscripten/system.c
  src/system/unix/system.c
  src/system/zephyr/system.c
Labels: bug, release

#760 Fix read/lease task cleanup
  src/transport/multicast/transport.c
  src/transport/unicast/transport.c
Labels: bug, internal

#761 Align ID string representation with zenoh (lowercase)
  src/collections/string.c
Labels: bug, internal

#755 Remove default parameters from z_closure
  examples/espidf/z_get.c
  examples/espidf/z_queryable.c
  examples/espidf/z_sub.c
  examples/freertos_plus_tcp/z_get.c
  examples/freertos_plus_tcp/z_queryable.c
  examples/freertos_plus_tcp/z_sub.c
  examples/freertos_plus_tcp/z_sub_st.c
  examples/unix/c11/z_get.c
  examples/unix/c11/z_get_attachment.c
  examples/unix/c11/z_info.c
  examples/unix/c11/z_queryable.c
  examples/unix/c11/z_queryable_attachment.c
  examples/unix/c11/z_sub.c
  examples/unix/c11/z_sub_attachment.c
  examples/unix/c11/z_sub_st.c
  examples/windows/z_get.c
  examples/windows/z_info.c
  examples/windows/z_queryable.c
  examples/windows/z_sub.c
  examples/windows/z_sub_st.c
  examples/zephyr/z_get.c
  examples/zephyr/z_queryable.c
  examples/zephyr/z_sub.c
  include/zenoh-pico/api/macros.h
  tests/z_test_fragment_rx.c
Labels: bug, api sync

#758 Add manual batching mechanism
  CMakeLists.txt
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/collections/vec.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  include/zenoh-pico/protocol/definitions/network.h
  include/zenoh-pico/session/utils.h
  include/zenoh-pico/transport/multicast/transport.h
  include/zenoh-pico/transport/multicast/tx.h
  include/zenoh-pico/transport/transport.h
  include/zenoh-pico/transport/unicast/transport.h
  include/zenoh-pico/transport/unicast/tx.h
  src/api/api.c
  src/collections/vec.c
  src/protocol/codec/declarations.c
  src/protocol/codec/transport.c
  src/protocol/definitions/network.c
  src/session/tx.c
  src/transport/multicast/rx.c
  src/transport/multicast/transport.c
  src/transport/multicast/tx.c
  src/transport/raweth/rx.c
  src/transport/raweth/tx.c
  src/transport/transport.c
  src/transport/unicast/rx.c
  src/transport/unicast/transport.c
  src/transport/unicast/tx.c
Labels: enhancement

#762 Switch multicast address to stack
  src/link/multicast/bt.c
  src/system/arduino/esp32/network.cpp
  src/system/arduino/opencr/network.cpp
  src/system/espidf/network.c
  src/system/mbed/network.cpp
  src/system/unix/link/raweth.c
  src/system/unix/network.c
  src/system/windows/network.c
  src/system/zephyr/network.c
  src/transport/multicast/read.c
Labels: enhancement

#763 Add local query timeout
  include/zenoh-pico/session/query.h
  include/zenoh-pico/session/session.h
  include/zenoh-pico/session/utils.h
  src/api/api.c
  src/net/primitives.c
  src/session/interest.c
  src/session/query.c
  src/session/queryable.c
  src/session/resource.c
  src/session/subscription.c
  src/session/utils.c
  src/transport/multicast/lease.c
  src/transport/unicast/lease.c
Labels: enhancement

#764 Add peer tcp unicast
  include/zenoh-pico/link/manager.h
  include/zenoh-pico/transport/manager.h
  include/zenoh-pico/transport/unicast/transport.h
  src/link/link.c
  src/link/unicast/tcp.c
  src/net/session.c
  src/system/unix/network.c
  src/transport/manager.c
  src/transport/unicast/read.c
  src/transport/unicast/transport.c
  tests/z_peer_multicast_test.c
Labels: enhancement

#765 Batching v2
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/protocol/core.h
  include/zenoh-pico/session/utils.h
  include/zenoh-pico/transport/common/tx.h
  include/zenoh-pico/transport/multicast/transport.h
  include/zenoh-pico/transport/multicast/tx.h
  include/zenoh-pico/transport/raweth/tx.h
  include/zenoh-pico/transport/transport.h
  include/zenoh-pico/transport/unicast/transport.h
  include/zenoh-pico/transport/unicast/tx.h
  src/api/api.c
  src/net/primitives.c
  src/net/query.c
  src/protocol/core.c
  src/session/interest.c
  src/session/rx.c
  src/session/tx.c
  src/session/utils.c
  src/transport/common/tx.c
  src/transport/multicast.c
  src/transport/multicast/lease.c
  src/transport/multicast/read.c
  src/transport/multicast/rx.c
  src/transport/multicast/transport.c
  src/transport/multicast/tx.c
  src/transport/raweth/read.c
  src/transport/raweth/rx.c
  src/transport/raweth/tx.c
  src/transport/transport.c
  src/transport/unicast.c
  src/transport/unicast/lease.c
  src/transport/unicast/read.c
  src/transport/unicast/rx.c
  src/transport/unicast/transport.c
  src/transport/unicast/tx.c
Labels: enhancement

#766 build both shared and static libraries when packaging
  CMakeLists.txt
  PackageConfig.cmake.in
  examples/CMakeLists.txt
  examples/freertos_plus_tcp/CMakeLists.txt
Labels: internal

#769 Publish debian packages
  .github/workflows/release.yml
  CMakeLists.txt
  GNUmakefile
  ci/scripts/build-linux.bash
Labels: internal
