Repository eclipse-zenoh/zenoh-pico, pull requests merged in 2024-12, with the labels that each got.

#819 Fix zephyr 4.0 version support
  include/zenoh-pico/system/platform/zephyr.h
  src/system/zephyr/network.c
Labels: internal

#813 feat: support start/stop fragment marker
  include/zenoh-pico/protocol/definitions/transport.h
  include/zenoh-pico/protocol/ext.h
  include/zenoh-pico/transport/common/tx.h
  include/zenoh-pico/transport/transport.h
  include/zenoh-pico/transport/utils.h
  src/protocol/codec/transport.c
  src/protocol/definitions/transport.c
  src/transport/common/tx.c
  src/transport/multicast/rx.c
  src/transport/multicast/tx.c
  src/transport/peer_entry.c
  src/transport/raweth/tx.c
  src/transport/unicast/rx.c
  src/transport/unicast/transport.c
  src/transport/unicast/tx.c
  src/transport/utils.c
  tests/z_msgcodec_test.c
Labels: new feature

#790 Implement clock in mbed port
  include/zenoh-pico/system/platform/mbed.h
  src/system/mbed/system.cpp
Labels: enhancement

#821 Implement condition variables for Mbed and FreeRTOS-Plus-TCP ports
  include/zenoh-pico/system/platform/freertos_plus_tcp.h
  src/system/freertos_plus_tcp/system.c
  src/system/mbed/system.cpp
Labels: enhancement

#824 Enable unstable API and all examples build for rpi_pico
  examples/rpi_pico/CMakeLists.txt
Labels: internal

#826 Fix z_bytes_clone memory leak
  src/collections/vec.c
Labels: bug

#822 FreeRTOS-Plus-TCP port fixes
  include/zenoh-pico/system/platform/freertos_plus_tcp.h
  src/system/freertos_plus_tcp/system.c
Labels: bug

#823 Update and improve serial protocol
  .github/workflows/arduino_esp32.yaml
  .github/workflows/espidf.yaml
  CMakeLists.txt
  examples/rpi_pico/main.c
  include/zenoh-pico/collections/arc_slice.h
  include/zenoh-pico/protocol/codec/serial.h
  include/zenoh-pico/protocol/definitions/serial.h
  include/zenoh-pico/system/common/platform.h
  include/zenoh-pico/system/common/serial.h
  include/zenoh-pico/system/link/serial.h
  include/zenoh-pico/system/platform.h
  include/zenoh-pico/system/platform/espidf.h
  include/zenoh-pico/utils/logging.h
  src/api/api.c
  src/link/unicast/serial.c
  src/protocol/codec/serial.c
  src/system/arduino/esp32/network.cpp
  src/system/arduino/esp32/system.c
  src/system/common/platform.c
  src/system/common/serial.c
  src/system/espidf/network.c
  src/system/flipper/network.c
  src/system/mbed/network.cpp
  src/system/rpi_pico/network.c
  src/system/unix/system.c
  src/system/zephyr/network.c
  tests/z_msgcodec_test.c
  tests/z_refcount_test.c
  zephyr/CMakeLists.txt
Labels: enhancement

#827 Fix liveliness CI test
  .github/workflows/build-check.yaml
  GNUmakefile
  examples/unix/c11/z_liveliness.c
  tests/memory_leak.py
Labels: internal

#829 Improve no_router test
  tests/no_router.py
Labels: enhancement, internal

#828 Fix ASAN build and enable it for examples
  CMakeLists.txt
Labels: bug, internal

#831 Update .gitignore
  .gitignore
Labels: internal

#834 Fix int conversion warning
  examples/unix/c11/z_liveliness.c
Labels: bug, internal

#832 fix: exclude internal from automatic changelog
  .github/release.yml
Labels: internal

#837 Add CI for checking markdown format.
  .github/workflows/build-check.yaml
  .markdownlint.yaml
  README.md
Labels: internal

#833 fix: Add CI status and change build-check to ci
  .github/workflows/build-shared.yaml
  .github/workflows/build-static.yaml
  .github/workflows/ci.yml
  .github/workflows/integration.yaml
  .github/workflows/multicast.yaml
Labels: internal

#838 add possibility to get contiguous view of z_bytes data when it is not fragmented
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  src/api/api.c
  tests/z_api_bytes_test.c
Labels: enhancement

#839 Fix interest initialization
  include/zenoh-pico/session/interest.h
  src/session/interest.c
  src/session/utils.c
Labels: bug

#665 Support waiting on condition variable until a specific time point
  include/zenoh-pico/system/common/platform.h
  include/zenoh-pico/utils/result.h
  src/system/arduino/esp32/system.c
  src/system/arduino/opencr/system.c
  src/system/common/platform.c
  src/system/emscripten/system.c
  src/system/espidf/system.c
  src/system/flipper/system.c
  src/system/freertos_plus_tcp/system.c
  src/system/mbed/system.cpp
  src/system/rpi_pico/system.c
  src/system/unix/system.c
  src/system/windows/system.c
  src/system/zephyr/system.c
Labels: enhancement

#840 Adjust rpi_pico default stack size
  .github/workflows/rpi_pico.yaml
  src/system/rpi_pico/system.c
Labels: enhancement, internal

#799 Implement connection restoring
  .github/workflows/ci.yml
  CMakeLists.txt
  include/zenoh-pico/collections/list.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  include/zenoh-pico/link/endpoint.h
  include/zenoh-pico/link/link.h
  include/zenoh-pico/net/session.h
  include/zenoh-pico/protocol/definitions/network.h
  include/zenoh-pico/session/utils.h
  include/zenoh-pico/transport/common/transport.h
  include/zenoh-pico/transport/manager.h
  include/zenoh-pico/transport/multicast/transport.h
  include/zenoh-pico/transport/transport.h
  include/zenoh-pico/transport/unicast/transport.h
  src/api/api.c
  src/collections/list.c
  src/link/endpoint.c
  src/link/link.c
  src/net/primitives.c
  src/net/session.c
  src/protocol/definitions/network.c
  src/protocol/definitions/transport.c
  src/session/rx.c
  src/session/utils.c
  src/system/rpi_pico/system.c
  src/transport/common/transport.c
  src/transport/manager.c
  src/transport/multicast/lease.c
  src/transport/multicast/transport.c
  src/transport/transport.c
  src/transport/unicast/lease.c
  src/transport/unicast/transport.c
  tests/connection_restore.py
Labels: enhancement

#841 Add lru cache
  CMakeLists.txt
  include/zenoh-pico/collections/lru_cache.h
  include/zenoh-pico/collections/string.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  include/zenoh-pico/net/primitives.h
  include/zenoh-pico/net/query.h
  include/zenoh-pico/net/session.h
  include/zenoh-pico/protocol/core.h
  include/zenoh-pico/protocol/keyexpr.h
  include/zenoh-pico/session/queryable.h
  include/zenoh-pico/session/resource.h
  include/zenoh-pico/session/subscription.h
  src/api/api.c
  src/collections/lru_cache.c
  src/collections/string.c
  src/net/liveliness.c
  src/net/primitives.c
  src/protocol/core.c
  src/protocol/keyexpr.c
  src/session/interest.c
  src/session/liveliness.c
  src/session/queryable.c
  src/session/resource.c
  src/session/rx.c
  src/session/subscription.c
  src/session/utils.c
  tests/z_lru_cache_test.c
Labels: enhancement

#842 Fix Wconversion errors
  src/system/unix/system.c
Labels: bug

#845 Fix liveliness timeout type
  include/zenoh-pico/api/liveliness.h
Labels: bug, api sync
