Repository eclipse-zenoh/zenoh-pico, pull requests merged in 2025-02, with the labels that each got.

#875 Refactor rx layer
  src/session/liveliness.c
  src/session/push.c
  src/session/reply.c
  src/session/rx.c
  src/transport/multicast/rx.c
  src/transport/unicast/rx.c
Labels: enhancement

#877 Fix 0 size allocation
  src/collections/slice.c
  src/protocol/definitions/transport.c
  src/system/freertos_plus_tcp/system.c
  src/system/rpi_pico/system.c
  src/transport/unicast/transport.c
Labels: bug

#881 Disable warning when matching enabled without unstable
  CMakeLists.txt
Labels: internal

#883 Fix Wconversion errors on querier example
  examples/unix/c11/z_querier.c
Labels: bug

#885 Add single thread support to z_api_matching_test
  tests/z_api_matching_test.c
Labels: enhancement

#886 Fix view ke examples
  examples/arduino/z_pull.ino
  examples/espidf/z_pull.c
  examples/freertos_plus_tcp/z_get.c
  examples/freertos_plus_tcp/z_pull.c
  examples/freertos_plus_tcp/z_queryable.c
  examples/mbed/z_pull.cpp
  examples/rpi_pico/z_get.c
  examples/rpi_pico/z_pub_thr.c
  examples/rpi_pico/z_pull.c
  examples/rpi_pico/z_queryable.c
  examples/rpi_pico/z_sub_thr.c
  examples/unix/c11/z_get.c
  examples/unix/c11/z_get_attachment.c
  examples/unix/c11/z_get_channel.c
  examples/unix/c11/z_get_liveliness.c
  examples/unix/c11/z_liveliness.c
  examples/unix/c11/z_pub.c
  examples/unix/c11/z_pub_attachment.c
  examples/unix/c11/z_pub_st.c
  examples/unix/c11/z_pub_thr.c
  examples/unix/c11/z_pull.c
  examples/unix/c11/z_put.c
  examples/unix/c11/z_querier.c
  examples/unix/c11/z_queryable.c
  examples/unix/c11/z_queryable_attachment.c
  examples/unix/c11/z_queryable_channel.c
  examples/unix/c11/z_sub.c
  examples/unix/c11/z_sub_attachment.c
  examples/unix/c11/z_sub_channel.c
  examples/unix/c11/z_sub_liveliness.c
  examples/unix/c11/z_sub_st.c
  examples/unix/c11/z_sub_thr.c
  examples/unix/c99/z_get.c
  examples/unix/c99/z_pub.c
  examples/unix/c99/z_pub_st.c
  examples/unix/c99/z_pull.c
  examples/unix/c99/z_put.c
  examples/unix/c99/z_queryable.c
  examples/unix/c99/z_sub.c
  examples/unix/c99/z_sub_st.c
  examples/windows/z_get.c
  examples/windows/z_pub.c
  examples/windows/z_pub_st.c
  examples/windows/z_pull.c
  examples/windows/z_put.c
  examples/windows/z_queryable.c
  examples/windows/z_sub.c
  examples/windows/z_sub_st.c
  examples/zephyr/z_pull.c
Labels: enhancement

#867 Fix transport tasks cleanup
  include/zenoh-pico/system/common/platform.h
  src/system/arduino/esp32/system.c
  src/system/arduino/opencr/system.c
  src/system/emscripten/system.c
  src/system/espidf/system.c
  src/system/flipper/system.c
  src/system/freertos_plus_tcp/system.c
  src/system/mbed/system.cpp
  src/system/rpi_pico/system.c
  src/system/unix/system.c
  src/system/windows/system.c
  src/system/zephyr/system.c
  src/transport/common/transport.c
  src/transport/unicast/lease.c
Labels: bug

#882 Fix single thread ring channel
  .github/workflows/ci.yml
  src/collections/ring_mt.c
  tests/z_channels_test.c
Labels: bug

#888 Remove obsolete config token
  CMakeLists.txt
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
Labels: enhancement

#891 Fix liveliness token registration
  src/net/liveliness.c
Labels: bug

#894 Adopt the different congestion control defaults as in Rust
  include/zenoh-pico.h
  include/zenoh-pico/api/constants.h
  library.json
  src/api/api.c
  tests/fragment.py
  zenohpico.pc
Labels: bug, internal

#895 Fix z_collections_test
  tests/z_collections_test.c
Labels: bug, internal

#903 make query clear account for take_from_loaned_query
  src/net/query.c
Labels: bug

#905 Fix null allocation in msgcodec
  .github/workflows/ci.yml
  src/collections/bytes.c
  tests/z_msgcodec_test.c
Labels: bug

#896 Add z_entity_global_id_t type
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  include/zenoh-pico/protocol/core.h
  src/api/api.c
Labels: enhancement

#906 Fix config issue
  CMakeLists.txt
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  src/api/api.c
Labels: bug
