Repository eclipse-zenoh/zenoh-pico, pull requests merged in 2025-01, with the labels that each got.

#848 Fix espidf sleep methods
  src/system/espidf/system.c
Labels: bug

#850 Update batching to stable.
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/protocol/definitions/network.h
  src/api/api.c
  src/transport/common/tx.c
Labels: enhancement

#851 Fix multicast configuration in embedded examples
  examples/arduino/z_get.ino
  examples/arduino/z_pub.ino
  examples/arduino/z_pull.ino
  examples/arduino/z_queryable.ino
  examples/arduino/z_sub.ino
  examples/espidf/z_get.c
  examples/espidf/z_pub.c
  examples/espidf/z_pull.c
  examples/espidf/z_queryable.c
  examples/espidf/z_sub.c
  examples/freertos_plus_tcp/z_get.c
  examples/freertos_plus_tcp/z_pub.c
  examples/freertos_plus_tcp/z_pub_st.c
  examples/freertos_plus_tcp/z_pull.c
  examples/freertos_plus_tcp/z_put.c
  examples/freertos_plus_tcp/z_queryable.c
  examples/freertos_plus_tcp/z_sub.c
  examples/freertos_plus_tcp/z_sub_st.c
  examples/mbed/z_get.cpp
  examples/mbed/z_pub.cpp
  examples/mbed/z_pull.cpp
  examples/mbed/z_queryable.cpp
  examples/mbed/z_sub.cpp
  examples/zephyr/z_get.c
  examples/zephyr/z_pub.c
  examples/zephyr/z_pull.c
  examples/zephyr/z_queryable.c
  examples/zephyr/z_sub.c
Labels: bug

#852 Fix typo in z_closure_zid_callback_t docs
  docs/api.rst
  include/zenoh-pico/api/primitives.h
Labels: internal

#853 Add matching subscribers
  .github/workflows/integration.yaml
  CMakeLists.txt
  docs/api.rst
  docs/conf.py
  examples/unix/c11/z_pub.c
  include/zenoh-pico/api/macros.h
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  include/zenoh-pico/net/matching.h
  include/zenoh-pico/net/session.h
  include/zenoh-pico/session/matching.h
  src/api/api.c
  src/net/matching.c
  src/net/primitives.c
  src/session/matching.c
  src/session/utils.c
  tests/memory_leak.py
  tests/z_api_matching_test.c
  tests/z_collections_test.c
Labels: new feature

#854 Add z_liveliness_declare_background_subscriber
  docs/api.rst
  include/zenoh-pico/api/liveliness.h
  src/api/liveliness.c
  src/session/liveliness.c
Labels: new feature, api sync

#857 Liveliness token drop/redeclaration on connection drop/restore
  include/zenoh-pico/net/primitives.h
  include/zenoh-pico/session/liveliness.h
  src/net/liveliness.c
  src/net/primitives.c
  src/session/liveliness.c
  src/transport/multicast/lease.c
  src/transport/unicast/lease.c
  tests/connection_restore.py
Labels: enhancement

#858 Implement querier
  CMakeLists.txt
  docs/api.rst
  examples/CMakeLists.txt
  examples/unix/c11/z_querier.c
  include/zenoh-pico/api/macros.h
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  include/zenoh-pico/net/primitives.h
  include/zenoh-pico/net/query.h
  src/api/api.c
  src/net/primitives.c
  src/net/query.c
  tests/memory_leak.py
Labels: new feature, api sync

#863 Report logs from routed test only on fail
  tests/routed.sh
Labels: internal

#869 Fix transport mutex initialization
  src/net/session.c
Labels: bug

#866 Fix serial open memory leak
  src/link/unicast/serial.c
Labels: bug

#872 Fix session mutex unlock on query reply
  src/session/query.c
Labels: bug

#873 Fix memory leaks
  include/zenoh-pico/collections/lru_cache.h
  include/zenoh-pico/collections/vec.h
  include/zenoh-pico/session/queryable.h
  include/zenoh-pico/session/subscription.h
  src/collections/lru_cache.c
  src/protocol/definitions/transport.c
  src/session/queryable.c
  src/session/rx.c
  src/session/subscription.c
  src/transport/multicast/read.c
  src/transport/multicast/rx.c
  src/transport/unicast/read.c
  src/transport/unicast/rx.c
  tests/z_lru_cache_test.c
Labels: bug
