Repository eclipse-zenoh/zenoh-pico, pull requests merged in 2025-03, with the labels that each got.

#907 Resolve AddressSanitizer issues in z_api_alignment_test
  tests/z_api_alignment_test.c
Labels: bug

#899 Add source info types and options
  .github/workflows/integration.yaml
  CMakeLists.txt
  GNUmakefile
  docs/api.rst
  include/zenoh-pico/api/macros.h
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/api/types.h
  include/zenoh-pico/net/primitives.h
  include/zenoh-pico/net/reply.h
  include/zenoh-pico/net/sample.h
  include/zenoh-pico/protocol/codec/core.h
  include/zenoh-pico/protocol/core.h
  include/zenoh-pico/session/subscription.h
  src/api/api.c
  src/net/primitives.c
  src/net/sample.c
  src/protocol/codec/message.c
  src/protocol/core.c
  src/protocol/definitions/message.c
  src/session/liveliness.c
  src/session/push.c
  src/session/query.c
  src/session/rx.c
  src/session/subscription.c
  tests/z_api_null_drop_test.c
  tests/z_api_source_info_test.c
  tests/z_msgcodec_test.c
Labels: enhancement

#904 channels use take_from_loaned instead of clone
  CMakeLists.txt
  include/zenoh-pico/api/handlers.h
  include/zenoh-pico/api/olv_macros.h
  include/zenoh-pico/collections/bytes.h
  include/zenoh-pico/collections/intmap.h
  include/zenoh-pico/collections/refcount.h
  include/zenoh-pico/collections/slice.h
  include/zenoh-pico/collections/string.h
  include/zenoh-pico/collections/vec.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  include/zenoh-pico/net/encoding.h
  include/zenoh-pico/net/query.h
  include/zenoh-pico/net/reply.h
  include/zenoh-pico/net/sample.h
  include/zenoh-pico/protocol/core.h
  include/zenoh-pico/protocol/keyexpr.h
  src/api/api.c
  src/api/serialization.c
  src/collections/bytes.c
  src/collections/slice.c
  src/collections/string.c
  src/net/encoding.c
  src/net/liveliness.c
  src/net/reply.c
  src/net/sample.c
  src/protocol/core.c
  src/protocol/ext.c
  src/protocol/keyexpr.c
  src/session/liveliness.c
  src/session/query.c
  src/session/queryable.c
  src/session/subscription.c
  tests/z_channels_test.c
Labels: enhancement, internal

#908 Update unicast tx
  include/zenoh-pico/system/common/platform.h
  include/zenoh-pico/system/platform/void.h
  include/zenoh-pico/transport/common/tx.h
  src/net/primitives.c
  src/system/arduino/esp32/network.cpp
  src/system/arduino/opencr/network.cpp
  src/system/emscripten/network.c
  src/system/espidf/network.c
  src/system/flipper/network.c
  src/system/freertos_plus_tcp/network.c
  src/system/mbed/network.cpp
  src/system/rpi_pico/network.c
  src/system/unix/network.c
  src/system/windows/network.c
  src/system/zephyr/network.c
  src/transport/common/tx.c
  src/transport/multicast/rx.c
  src/transport/multicast/transport.c
  src/transport/peer_entry.c
  src/transport/unicast/accept.c
  src/transport/unicast/lease.c
  src/transport/unicast/read.c
  src/transport/unicast/transport.c
Labels: enhancement

#910 Improve unicast tx
  include/zenoh-pico/system/common/platform.h
  include/zenoh-pico/system/platform/arduino/esp32.h
  include/zenoh-pico/system/platform/emscripten.h
  include/zenoh-pico/system/platform/espidf.h
  include/zenoh-pico/system/platform/flipper.h
  include/zenoh-pico/system/platform/freertos_plus_tcp.h
  include/zenoh-pico/system/platform/mbed.h
  include/zenoh-pico/system/platform/rpi_pico.h
  include/zenoh-pico/system/platform/unix.h
  include/zenoh-pico/system/platform/void.h
  include/zenoh-pico/system/platform/windows.h
  include/zenoh-pico/system/platform/zephyr.h
  include/zenoh-pico/transport/transport.h
  src/protocol/codec/ext.c
  src/protocol/codec/message.c
  src/protocol/codec/transport.c
  src/protocol/definitions/transport.c
  src/protocol/ext.c
  src/system/arduino/esp32/system.c
  src/system/arduino/opencr/system.c
  src/system/emscripten/system.c
  src/system/espidf/system.c
  src/system/freertos_plus_tcp/system.c
  src/system/mbed/system.cpp
  src/system/rpi_pico/system.c
  src/system/unix/system.c
  src/system/windows/system.c
  src/system/zephyr/system.c
  src/transport/common/transport.c
  src/transport/common/tx.c
  src/transport/multicast/transport.c
  src/transport/peer_entry.c
  src/transport/unicast/read.c
  src/transport/unicast/rx.c
  src/transport/unicast/transport.c
Labels: enhancement

#914 Allow multiple connect
  CMakeLists.txt
  include/zenoh-pico/collections/intmap.h
  include/zenoh-pico/config.h
  include/zenoh-pico/config.h.in
  include/zenoh-pico/link/link.h
  include/zenoh-pico/link/manager.h
  include/zenoh-pico/transport/manager.h
  include/zenoh-pico/transport/transport.h
  include/zenoh-pico/transport/unicast/transport.h
  include/zenoh-pico/utils/config.h
  src/api/api.c
  src/collections/intmap.c
  src/link/link.c
  src/link/unicast/tcp.c
  src/net/primitives.c
  src/net/session.c
  src/protocol/config.c
  src/transport/common/transport.c
  src/transport/manager.c
  src/transport/multicast/transport.c
  src/transport/unicast/accept.c
  src/transport/unicast/transport.c
  tests/z_api_liveliness_test.c
Labels: enhancement

#912 Run memory leak on unit tests
  .github/workflows/ci.yml
  tests/z_msgcodec_test.c
Labels: enhancement

#916 Make channels ref-counted
  include/zenoh-pico/api/handlers.h
  include/zenoh-pico/api/olv_macros.h
  include/zenoh-pico/collections/fifo_mt.h
Labels: enhancement

#913 fix _z_open_serial_from_dev in zephyr
  src/system/zephyr/network.c
  src/transport/multicast/transport.c
  src/transport/unicast/transport.c
Labels: bug

#921 Fix conditional compilation issues
  .github/workflows/ci.yml
  CMakeLists.txt
  include/zenoh-pico/net/publish.h
  include/zenoh-pico/net/query.h
  src/transport/multicast/transport.c
Labels: bug
