Repository eclipse-zenoh/zenoh-pico, pull requests merged in 2025-04, with the labels that each got.

#929 Listener refuse client connections.
  src/transport/unicast/transport.c
Labels: bug

#933 Zenoh generic - make zenoh-pico generic across most platformio platforms
  docs/generic_platform.md
  extra_script.py
  include/zenoh-pico/config.h
  include/zenoh-pico/system/common/platform.h
  library.json
Labels: enhancement

#935 Prevent int underflow in link write
  src/link/link.c
Labels: bug

#932 Add LWIP network for FreeRTOS system
  CMakeLists.txt
  extra_script.py
  include/zenoh-pico/system/common/platform.h
  include/zenoh-pico/system/platform/freertos/freertos_plus_tcp.h
  include/zenoh-pico/system/platform/freertos/lwip.h
  src/system/freertos/freertos_plus_tcp/network.c
  src/system/freertos/lwip/network.c
  src/system/freertos/system.c
Labels: enhancement

#937 Add generic platform to config.h.in
  include/zenoh-pico/config.h.in
Labels: bug

#941 Fix platformio config issues
  .github/workflows/arduino_esp32.yaml
  .github/workflows/espidf.yaml
  .github/workflows/mbed.yaml
  .github/workflows/zephyr.yaml
  CMakeLists.txt
  extra_script.py
  src/protocol/codec/network.c
  src/system/mbed/network.cpp
  src/system/unix/network.c
  tests/z_msgcodec_test.c
Labels: bug

#931 expose Z_FEATURE_BATCHING in PackageConfig.cmake
  PackageConfig.cmake.in
Labels: internal

#940 Resolve issue with invalid pointer dereference when dropping session when building with Address Sanitizer active.
  src/transport/multicast/transport.c
  src/transport/unicast/transport.c
Labels: bug

#943 Only include headers if Z_FEATURE_RAWETH_TRANSPORT set.
  src/system/unix/link/raweth.c
Labels: internal

#947 add z_queryable_keyexpr
  CMakeLists.txt
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  src/api/api.c
  tests/z_api_queryable_test.c
Labels: enhancement, api sync

#951 Fix FreeRTOS/lwip when using Multi Thread
  include/zenoh-pico/system/platform/freertos/lwip.h
Labels: bug

#950 Fix FreeRTOS/LWIP when using UDP Multicast
  src/system/freertos/lwip/network.c
Labels: bug

#952 Fix task cancel race condition, on ESP32, causing core panic
  include/zenoh-pico/system/platform/arduino/esp32.h
  src/system/arduino/esp32/system.c
Labels: bug

#946 Rework lru cache insertion
  src/collections/lru_cache.c
  tests/z_lru_cache_test.c
Labels: enhancement
