Repository eclipse-zenoh/zenoh-pico, pull requests merged in 2025-06, with the labels that each got.

#971 Mark source_info as unstable in API documentation.
  include/zenoh-pico/api/primitives.h
Labels: documentation

#973 examples: properly check result code
  examples/unix/c11/z_get_lat.c
Labels: internal

#975 Add slist
  examples/unix/c11/z_get_lat.c
  examples/unix/c11/z_ping.c
  include/zenoh-pico/collections/list.h
  include/zenoh-pico/net/filtering.h
  include/zenoh-pico/net/reply.h
  include/zenoh-pico/net/session.h
  include/zenoh-pico/protocol/core.h
  include/zenoh-pico/protocol/definitions/network.h
  include/zenoh-pico/session/query.h
  include/zenoh-pico/session/session.h
  include/zenoh-pico/session/utils.h
  include/zenoh-pico/transport/common/tx.h
  include/zenoh-pico/transport/transport.h
  src/api/api.c
  src/collections/intmap.c
  src/collections/list.c
  src/net/filtering.c
  src/net/primitives.c
  src/net/session.c
  src/protocol/config.c
  src/session/interest.c
  src/session/query.c
  src/session/queryable.c
  src/session/resource.c
  src/session/scout.c
  src/session/subscription.c
  src/session/utils.c
  src/system/arduino/esp32/network.cpp
  src/system/espidf/network.c
  src/system/freertos/freertos_plus_tcp/network.c
  src/system/freertos/lwip/network.c
  src/system/rpi_pico/network.c
  src/system/unix/network.c
  src/system/windows/network.c
  src/system/zephyr/network.c
  src/transport/common/tx.c
  src/transport/multicast.c
  src/transport/multicast/lease.c
  src/transport/multicast/rx.c
  src/transport/multicast/transport.c
  src/transport/peer.c
  src/transport/unicast.c
  src/transport/unicast/accept.c
  src/transport/unicast/lease.c
  src/transport/unicast/read.c
  src/transport/unicast/rx.c
  src/transport/unicast/transport.c
  tests/z_client_test.c
  tests/z_collections_test.c
  tests/z_data_struct_test.c
Labels: enhancement
