Repository eclipse-zenoh/zenoh-pico, pull requests merged in 2025-07, with the labels that each got.

#983 Fix scout peer op
  src/net/session.c
  src/transport/multicast/rx.c
  src/transport/unicast/transport.c
Labels: bug

#988 ci: run apt-update before valgrind install
  .github/workflows/ci.yml
Labels: internal

#989 ci: don't pass codacy token
  .github/workflows/codacy-analysis.yml
Labels: internal

#991 stabilize querier and matching
  CMakeLists.txt
  examples/unix/c11/z_querier.c
  include/zenoh-pico/api/primitives.h
  src/api/api.c
Labels: enhancement, api sync

#993 Updated codacy CI job to upload individual result files.
  .github/workflows/codacy-analysis.yml
Labels: internal

#994 Add z_get_with_parameters_substr and z_querier_get_with_parameters_substr
  docs/api.rst
  include/zenoh-pico/api/primitives.h
  include/zenoh-pico/net/primitives.h
  src/api/api.c
  src/net/primitives.c
Labels: enhancement, api sync

#999 Fix liveliness declaration
  src/api/liveliness.c
  src/net/liveliness.c
Labels: bug

#1004 *IMPORTANT* Change default behavior of zp_read
  include/zenoh-pico/api/types.h
  include/zenoh-pico/net/session.h
  include/zenoh-pico/transport/common/read.h
  include/zenoh-pico/transport/multicast/read.h
  include/zenoh-pico/transport/raweth/read.h
  include/zenoh-pico/transport/unicast/read.h
  src/api/api.c
  src/net/session.c
  src/transport/common/read.c
  src/transport/multicast/read.c
  src/transport/raweth/read.c
  src/transport/unicast/read.c
Labels: enhancement

#1006 Fix undeclare of liveliness subscriber.
  src/net/primitives.c
  src/net/session.c
Labels: bug
